In [1]:
import numpy as np
from numpy import random

# Creating Numpy Arrays

In [2]:
# Creates a range from 0 to 9
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
# Create a range from 12 to 42, step 2
a2 = np.arange(12, 42, 2)
print(a2)

[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [4]:
# Matrix intialized with 0
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
# 2D - matrix with 0
a4 = np.zeros((2, 3))
print(a4)
print(a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [6]:
# To initialize matrix with any number
a5 = np.full((2, 3), 8)
print(a5)
print(a5.shape)

[[8 8 8]
 [8 8 8]]
(2, 3)


In [7]:
# To create identity matrix
a6 = np.eye(4)
print(a6)
print(a6.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [8]:
# Array of random values with 2 rows & 4 columns
a7 = np.random.random((2, 4))
print(a7)
print(a7.shape)

[[0.68666595 0.38676464 0.29618395 0.73870286]
 [0.46888544 0.50491041 0.85839242 0.51611342]]
(2, 4)


In [9]:
# Creating numpy array from python list
list1 = [1, 2, 3, 4, 5]
a8 = np.array(list1)
print(a8)

[1 2 3 4 5]


# Array Indexing

In [10]:
list2 = [6, 7, 8, 9, 10]
a9 = np.array([list1, list2])
print(a9)
print(a9.shape)
print(a9[0, 0])
print(a9[1, 3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
1
9


# Boolean Indexing

In [11]:
print(a9 > 2)

[[False False  True  True  True]
 [ True  True  True  True  True]]


In [12]:
print(a9[a9 > 2])

[ 3  4  5  6  7  8  9 10]


In [13]:
a10 = np.arange(20)
print(a10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
odd_num = a10[a10 % 2 == 1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


# Slicing Array

In [15]:
a = np.array([[1, 2, 3, 4, 5],
             [4, 15, 16, 7, 8],
             [9, 18, 17, 6, 5]])
print(a)

[[ 1  2  3  4  5]
 [ 4 15 16  7  8]
 [ 9 18 17  6  5]]


In [16]:
# row 1 to 3
b = a[1:3, :3]
print(b)  

[[ 4 15 16]
 [ 9 18 17]]


In [17]:
c = a[-2: , -2:]
print(c)

[[7 8]
 [6 5]]


# Reshaping Arrays

In [18]:
# Rank 1 array b1
b1 = np.array([9, 8, 7, 6, 5])
b1

array([9, 8, 7, 6, 5])

In [19]:
# Reshaping rank 1 array b1 to rank 2 array b2
b2 = b1.reshape(1, -1)
b2

array([[9, 8, 7, 6, 5]])

In [20]:
b3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b4 = b3.reshape(3, 4)
b4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
b5 = b3.reshape(2, 3, 2)
b5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [22]:
b6 = b5.reshape(-1, )
b6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
b7 = b5.flatten('F')
b7

array([ 1,  7,  3,  9,  5, 11,  2,  8,  4, 10,  6, 12])

# Array Math

In [24]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
y1 = np.array([[7, 8, 9], [2, 3, 4]])

In [25]:
x1 + y1

array([[ 8, 10, 12],
       [ 6,  8, 10]])

In [26]:
np.add(x1, y1)

array([[ 8, 10, 12],
       [ 6,  8, 10]])

In [27]:
x1 - y1

array([[-6, -6, -6],
       [ 2,  2,  2]])

In [28]:
x1 * y1

array([[ 7, 16, 27],
       [ 8, 15, 24]])

# Dot Product

In [29]:
x2 = np.array([2, 3])
y2 = np.array([4, 2])

In [30]:
np.dot(x2, y2)     # 2*4 + 3*2

14

In [31]:
x3 = np.array([[1, 2, 3], [4, 5, 6]])
y3 = np.array([[7, 8], [9, 10], [11, 12]])

In [32]:
x3

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
y3

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
np.dot(x3, y3)    # (1*7 + 2*9 + 3*11), (4*7 + 5*9 + 6*11) , (1*8 + 2*10 + 3*12), (4*8 + 5*10 + 6*12)

array([[ 58,  64],
       [139, 154]])

# Numpy Matrix

In [35]:
mx1 = np.array([[1, 2], [4, 5]])
mx2 = np.array([[7, 8], [2, 3]])

mx1 * mx2

array([[ 7, 16],
       [ 8, 15]])

In [36]:
my1 = np.matrix([[1, 2], [4, 5]])
my2 = np.matrix([[7, 8], [2, 3]])

# dot product
my1 * my2           

matrix([[11, 14],
        [38, 47]])

# Cumulative Sum

In [37]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [39]:
x.cumsum(axis = 0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [40]:
x.cumsum(axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

# Numpy Sorting

In [41]:
age1 = np.array([34, 16, 12, 54, 78, 20])

In [42]:
# Outplace sorting
age = np.sort(age1)
print("Actual Array: ", age1)
print("Sorted Array: ", age)

Actual Array:  [34 16 12 54 78 20]
Sorted Array:  [12 16 20 34 54 78]


In [43]:
# Inplace sorting
age1.sort()
print(age1)

[12 16 20 34 54 78]


In [44]:
age2 = np.array([34, 16, 12, 54, 78, 20])

# Ranking of array
age2.argsort()

array([2, 1, 5, 0, 3, 4])

# Join Array

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [46]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [47]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [48]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [50]:
np.stack((arr1, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
np.stack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [53]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.dstack((arr1, arr2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Splitting Arrays

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [56]:
 # Split array into 3 using array_split
 np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [57]:
 # Split array into 3 using split
 # Split Function will not work when elements are less
 np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [58]:
# Split array into 4
np.array_split(arr, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Numpy Random

In [59]:
# Generate random integer from 0 to 50
a = random.randint(50)
a

24

In [60]:
# Generate random float between 0 to 1
b = random.rand()
b

0.956396315004317

In [61]:
# Generate array of 5 random integer from 0 to 50
c = random.randint(50, size=(5))
c

array([18, 29,  5, 37,  3])

In [62]:
# Generate array of 3x5 random integer from 0 to 100
d = random.randint(100, size=(3, 5))
d

array([[98, 88, 85, 71, 94],
       [19, 60, 69,  5, 98],
       [28, 33, 94, 23, 80]])

In [63]:
# Generate 5 random float between 0 to 1
e = random.rand(5)
e

array([0.86880563, 0.58088638, 0.90926086, 0.05820007, 0.60292682])

In [64]:
# Select random value from an array of choice
f = random.choice([3, 5, 7, 9])
f

3

In [65]:
# Generate 2d-array 3*5 of random numbers from a given array
g = random.choice([3, 5, 7, 9], size=(3, 5))
g

array([[7, 9, 9, 3, 5],
       [5, 3, 5, 5, 5],
       [7, 9, 5, 7, 3]])